spring:
  #设置数据库相关信息
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/book_ticket?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: admin

  #thymeleaf设置缓存为false,方便修改页面
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  #热部署
  devtools:
      restart:
        #是否启用重启
        enabled: true
        #设置重启的目录
        additional-paths: src/main/java,resources/**,static/**,templates/**
